apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - employee
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: scylla
          image: scylladb/scylla
          ports:
            - containerPort: 9042

---

apiVersion: v1
kind: Service
metadata:
  name: some-scylla
  namespace: database
spec:
  ports:
    - name: tcp
      port: 9042
      targetPort: 9042
  selector:
    app: scylla
