apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: attendance
data:
  data_url: "some-postgres.database.svc.cluster.local:5432"
  redis_url: "some-redis.database.svc.cluster.local"
  
  
