apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance
  namespace: attendance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-192-168-0-69.us-east-2.compute.internal
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - postgres
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: attendance
          image: aayush808/attendance-api:v1
          ports:
            - containerPort: 8080
          env:
          - name: data_url
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: data_url
          - name: redis_url
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: redis_url

---

apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: attendance
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: attendance
  type: LoadBalancer

